version: 43.0.9
pageUuid: 83cc9606-18bb-11ed-ad9d-e395d07d7f05
appTemplate:
  mobileAppSettings:
    object:
      mobileOfflineModeEnabled: false
  appThemeId: 5143
  experimentalFeatures:
    object:
      sourceControlTemplateDehydration: false
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
      skipDepCycleCheckingEnabled: false
      serverDepGraphEnabled: false
      useRuntimeV2: false
  version: 2.123.0
  experimentalDataTabEnabled: true
